In [1]:
import pandas as pd

df = pd.read_csv("logs/semantic_episodes_lggsn.csv")
df

,time,query,mode,obj_id,target_id,x,y,z,roll,pitch,yaw,width,obj_height
0,2025-11-22 11:16:36,tomato soup,tray,9,9.0,0.434477,-0.684260,0.786734,0.0,0.0,-1.457436,0.031264,0.001734
1,2025-11-22 11:18:11,chips,tray,16,16.0,-0.052888,-0.749242,0.854148,0.0,0.0,-1.515838,0.029575,0.069148
2,2025-11-22 11:18:29,tennis,tray,6,6.0,-0.186462,-0.597617,0.841025,0.0,0.0,-0.500452,0.038045,0.056025
3,2025-11-22 11:19:31,sauce\,tray,10,10.0,0.221480,-0.742022,0.822180,0.0,0.0,-0.461561,0.048281,0.037180

In [2]:
df["query"].value_counts()

query
tomato soup    1
chips          1
tennis         1
sauce\         1
Name: count, dtype: int64

In [3]:
df[["x","y","z","yaw","width"]].describe()

              x         y         z       yaw     width
count  4.000000  4.000000  4.000000  4.000000  4.000000
mean   0.104152 -0.693285  0.826022 -0.983822  0.036791
std    0.278088  0.070096  0.029295  0.581307  0.008489
min   -0.186462 -0.749242  0.786734 -1.515838  0.029575
25%   -0.086282 -0.743827  0.813318 -1.472037  0.030841
50%    0.084296 -0.713141  0.831603 -0.978944  0.034654
75%    0.274729 -0.662599  0.844306 -0.490729  0.040604
max    0.434477 -0.597617  0.854148 -0.461561  0.048281